apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dr52lco4s-go 
  janus-idp.io/tekton: dr52lco4s-go
  backstage.io/kubernetes-id: dr52lco4s-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dr52lco4s-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml