apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dr52lco4s-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:ef41760e35e05645217aefa5e1884d8540dd058a@sha256:a619ae7c465606de74473a77f0d9b3c35d23aea936bcbd1cf2a870d28d0b4080
          name: container-image
